console.log(3 == 3);
console.log(true);
console.log(4 == 3);
console.log(false);
console.log(3 * 3 + 1 == 11);
console.log(false);
 // Esta linha contém um erro de sintaxe, portanto não é possível incluí-la dentro de um console.log
console.log(3 * 3 + 1 == 10);
console.log(true);
console.log(3 * 3 + 1 === 10);
console.log(true);
console.log(3 * 3 + 1 === 11);
console.log(false);
console.log(10 === "10");
console.log(false);
console.log(3 != 3);
console.log(false);
console.log(3 != "3");
console.log(false);
console.log(3 !== "3");
console.log(true);